# Generated by Django 4.2.16 on 2025-09-29 08:48

from django.db import migrations, models
import mumble_rest.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "token",
                    mumble_rest.models.ClientSecretField(
                        blank=True,
                        db_index=True,
                        default=mumble_rest.models.generate_token,
                        help_text="Hashed on Save. Copy it now if this is a new secret.",
                        max_length=255,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "default_permissions": [],
            },
        ),
    ]
